# Wormlogic Hyprland config
# Host package: hosts/laptop01/arch/hypr

source = ~/.config/hypr/conf.d/00-monitors.conf
source = ~/.config/hypr/conf.d/10-programs.conf
source = ~/.config/hypr/conf.d/20-autostart.conf
source = ~/.config/hypr/conf.d/30-env.conf
source = ~/.config/hypr/conf.d/40-appearance.conf
source = ~/.config/hypr/conf.d/50-input.conf
source = ~/.config/hypr/conf.d/60-binds.conf
source = ~/.config/hypr/conf.d/70-rules.conf
source = ~/.config/hypr/conf.d/80-xwayland.conf
