# There are 5 monitor assignments because the D6000 assigns
# one of three names at random for one of the ports.

monitor = eDP-1,preferred,auto,1.2
monitor = DP-2,preferred,auto,1.25
monitor = DVI-I-1,preferred,auto,1.25
monitor = DVI-I-2,preferred,auto,1.25
monitor = DP-1,preferred,auto,1.25
